export const themes = [
  {
    id: "light",
    name: "清雅白",
    icon: "sun",
    accent: "#2563eb",
    vars: {
      "--bg": "#f8fafc",
      "--panel": "#ffffff",
      "--soft": "#f1f5f9",
      "--text": "#0f172a",
      "--muted": "#64748b",
      "--line": "#e2e8f0",
      "--accent": "#2563eb",
      "--accent-soft": "#dbeafe",
      "--code-bg": "#0f172a",
      "--code-text": "#e2e8f0",
      "--shadow": "0 22px 55px rgba(15,23,42,.08)",
    },
  },
  {
    id: "ink",
    name: "墨黑夜读",
    icon: "moon",
    accent: "#a78bfa",
    vars: {
      "--bg": "#09090b",
      "--panel": "#18181b",
      "--soft": "#27272a",
      "--text": "#fafafa",
      "--muted": "#a1a1aa",
      "--line": "#3f3f46",
      "--accent": "#a78bfa",
      "--accent-soft": "#2e1065",
      "--code-bg": "#020617",
      "--code-text": "#e5e7eb",
      "--shadow": "0 22px 55px rgba(0,0,0,.35)",
    },
  },
  {
    id: "paper",
    name: "暖纸笔记",
    icon: "book",
    accent: "#b45309",
    vars: {
      "--bg": "#fbf3e4",
      "--panel": "#fffaf0",
      "--soft": "#f7e8c8",
      "--text": "#342313",
      "--muted": "#8a6a43",
      "--line": "#ead7b7",
      "--accent": "#b45309",
      "--accent-soft": "#fed7aa",
      "--code-bg": "#2d1b0e",
      "--code-text": "#fff7ed",
      "--shadow": "0 22px 55px rgba(120,53,15,.12)",
    },
  },
  {
    id: "terminal",
    name: "终端青",
    icon: "layers",
    accent: "#22d3ee",
    vars: {
      "--bg": "#061014",
      "--panel": "#0b1f26",
      "--soft": "#10323b",
      "--text": "#e6fffb",
      "--muted": "#8dd9d2",
      "--line": "#164e58",
      "--accent": "#22d3ee",
      "--accent-soft": "#083344",
      "--code-bg": "#020617",
      "--code-text": "#cffafe",
      "--shadow": "0 22px 55px rgba(0,0,0,.38)",
    },
  },
  {
    id: "ocean",
    name: "海盐蓝",
    icon: "sun",
    accent: "#0ea5e9",
    vars: {
      "--bg": "#eef8ff",
      "--panel": "#ffffff",
      "--soft": "#dff3ff",
      "--text": "#082f49",
      "--muted": "#3f6f8f",
      "--line": "#bae6fd",
      "--accent": "#0ea5e9",
      "--accent-soft": "#e0f2fe",
      "--code-bg": "#082f49",
      "--code-text": "#e0f2fe",
      "--shadow": "0 22px 55px rgba(14,165,233,.13)",
    },
  },
  {
    id: "forest",
    name: "松林绿",
    icon: "book",
    accent: "#059669",
    vars: {
      "--bg": "#f0fdf4",
      "--panel": "#ffffff",
      "--soft": "#dcfce7",
      "--text": "#052e16",
      "--muted": "#3f6f55",
      "--line": "#bbf7d0",
      "--accent": "#059669",
      "--accent-soft": "#d1fae5",
      "--code-bg": "#052e16",
      "--code-text": "#dcfce7",
      "--shadow": "0 22px 55px rgba(5,150,105,.12)",
    },
  },
  {
    id: "dusk",
    name: "霞光紫",
    icon: "sparkles",
    accent: "#c026d3",
    vars: {
      "--bg": "#fff7ed",
      "--panel": "#fffafd",
      "--soft": "#fae8ff",
      "--text": "#3b0764",
      "--muted": "#7e4b8f",
      "--line": "#f5d0fe",
      "--accent": "#c026d3",
      "--accent-soft": "#fae8ff",
      "--code-bg": "#3b0764",
      "--code-text": "#fae8ff",
      "--shadow": "0 22px 55px rgba(192,38,211,.12)",
    },
  },
  {
    id: "graphite",
    name: "石墨灰",
    icon: "moon",
    accent: "#94a3b8",
    vars: {
      "--bg": "#111827",
      "--panel": "#1f2937",
      "--soft": "#374151",
      "--text": "#f9fafb",
      "--muted": "#cbd5e1",
      "--line": "#4b5563",
      "--accent": "#94a3b8",
      "--accent-soft": "#334155",
      "--code-bg": "#030712",
      "--code-text": "#f8fafc",
      "--shadow": "0 22px 55px rgba(0,0,0,.36)",
    },
  },
];

export const defaultThemeId = "light";

export function getThemeById(themeId) {
  return themes.find((theme) => theme.id === themeId) || themes[0];
}

export function isKnownTheme(themeId) {
  return themes.some((theme) => theme.id === themeId);
}
